
SERVER_HOST = 'localhost'
SERVER_PORT = 34455

WINDOW_SIZE_DEFAULT = (800, 600)
WINDOW_TITLE = 'My Game'

FPS_TARGET = 60

HEX_RADIUS_DEFAULT = 8
HEX_RADIUS_MID = 14
HEX_RADIUS_MIN = 2
HEX_RADIUS_MAX = 32

FONT_NAME_DEFAULT = 'monospace'
FONT_SIZE_DEFAULT = 20
